use_frameworks!

platform :ios, '9.0'

target 'JDMcdnSDK_Example' do
  pod 'JDMcdnSDK', :path => '../'

  target 'JDMcdnSDK_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
